### PR TITLE
Update to latest from upstream, and fix C++ 98 incompatibility.

### PR DESCRIPTION
**Pull request by ned14**

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
Please rebase it, so we don't have merge commit in history.

**Comment by ned14** [comment]
I'll be honest in saying that I'm not entirely sure I did the rebase right, best not to merge until I've verified.

**Comment by ned14** [comment]
I think this is now correct. The merge conflict is between the old pull request and the new rebased one, not between the new rebased branch and hunter.

**Comment by ruslo** [comment]
> I think this is now correct

Nope:

> Conflicting files
> rapidxml_iterators.hpp

Please take a look: https://github.com/hunter-packages/rapidxml/pull/2

In particular this part: https://github.com/hunter-packages/rapidxml/pull/2/commits/017688173044741abf9e75dbb82e673bcafdc2cb (I guess that's the fix you want to apply).

**Comment by ned14** [comment]
Ok, so what I'm interpreting from your feedback here is that you want the PR split into two PRs, one to fix the C++ 98 compatibility, the other to bring the package up to latest from upstream? If this is a correct interpretation, shall I rebase this PR on top of #2?

**Comment by ruslo** [comment]
> Ok, so what I'm interpreting from your feedback here is that you want the PR split into two PRs, one to fix the C++ 98 compatibility, the other to bring the package up to latest from upstream?

No, I don't want them split. I just want to keep history clean and remove merge commit. Originally it was:
- a134850
- 0a082b7
- e08cc85
- "... some merge commit ..."
- "Fix use of non-spaced template >> which was upsetting GCC 4.4." commit

> If this is a correct interpretation, shall I rebase this PR on top of #2?

No, just approve https://github.com/hunter-packages/rapidxml/pull/2 , I will merge it and release. This one we can close (Unless you want to add more commits).

**Comment by ned14** [comment]
> No, just approve #2 , I will merge it and release. This one we can close (Unless you want to add more commits).

You don't want to merge latest changes from upstream? Ok, no bother, the code here is happy without. Thanks for accepting the GCC 4.4 fix.

**Comment by ruslo** [comment]
> You don't want to merge latest changes from upstream?

I have updated up to `3ade903` (that where this PR started originally). Do you need more? Usually, it better to use the stable release, that what users expect to see. But if there is a good reason to fetch something fresher we can do it.

**Comment by ned14** [comment]
No need. We have differing git habits and evaluations of stability risk, that's all. I am fine with your choices here.

**Pull request closed without merging**
